[tool.poetry]
name = "configfactory"
version = "0.1.0"
description = ""
authors = ["Anton Ruhlov <antonruhlov@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "3.1b1"

[tool.poetry.dev-dependencies]
isort = "^5.0.7"
mypy = "^0.782"
black = "^19.10b0"
flake8 = "^3.8.3"

[tool.poetry.scripts]
configfactory = "configfactory.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
